FROM maven:3.3-jdk-8
COPY . /app
WORKDIR /app/
# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku			
# CMD gunicorn --bind 0.0.0.0:$PORT wsgi 
RUN useradd -m myuser
USER myuser
CMD java -Dserver.port=$PORT -jar target/loc-time-0.0.1-SNAPSHOT.jar



